# Site settings
title: Steve Bargelt
email: steve@bargelt.com
description: > # this means to ignore newlines until "baseurl:"
        Copyright &copy; Steve Bargelt 2016
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stevebargelt.com" # the base hostname & protocol for your site
twitter_username: stevebargelt
github_username:  stevebargelt
linkedin_url: stevebargelt

collections:
    portfolio:
    photo_gallery: 
    posts:
        output:   true

show_drafts: false

# Build settings
markdown: kramdown
text:
  pagination:
    newer: 'Newer Posts'
    older: 'Older Posts'

permalink:    /blog/:year/:month/:day/:title/
paginate:     5
paginate_path: "/blog/page:num/"
gems:
  - jekyll-paginate